"""empty message

Revision ID: 19af3807842c
Revises: 344830c507e3
Create Date: 2014-01-23 20:05:21.878187

"""

# revision identifiers, used by Alembic.
revision = '19af3807842c'
down_revision = '344830c507e3'

from bamboo.alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
