"""empty message

Revision ID: 290e4030a25a
Revises: 5185fd791028
Create Date: 2014-02-20 10:12:43.012385

"""

# revision identifiers, used by Alembic.
revision = '290e4030a25a'
down_revision = '5185fd791028'

from bamboo.alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
