"""empty message

Revision ID: 41509b91e126
Revises: 6cd62673a88
Create Date: 2014-01-21 14:55:54.285442

"""

# revision identifiers, used by Alembic.
revision = '41509b91e126'
down_revision = '6cd62673a88'

from bamboo.alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_details', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['name'])
    op.create_unique_constraint(None, 'users', ['openid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_constraint(None, 'users')
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('user_details', 'updated_at')
    op.drop_column('user_details', 'created_at')
    ### end Alembic commands ###
